# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieList' do
  use_frameworks!

  pod 'SnapKit'
  pod 'RxSwift'
  pod 'Alamofire', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'IQKeyboardManagerSwift'

  target 'MovieListTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'Mimus'
  end
end
